name: TestingInConda

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0

    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: 2025-sustech-simpeg
        channels: conda-forge
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}

    - name: Run Tests
      shell: bash
      run: |
        pip install testipynb
        pytest .
