name: Test with conda

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        init-shell: >-
          bash
          powershell
        create-args: >-
          python=${{ matrix.python-version }}
        cache-environment: true
        post-cleanup: 'all'
    - name: Run Tests
      shell: micromamba-shell {0}
      run: |
        pip install testipynb
        pytest . -v
